"""empty message

Revision ID: 99761ee2767d
Revises: 9d4664e1c189
Create Date: 2021-05-28 19:04:28.571405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99761ee2767d'
down_revision = '9d4664e1c189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting_drivers',
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('uuid', sa.String(length=80), nullable=False),
    sa.Column('generic', sa.Boolean(create_constraint=80), nullable=False),
    sa.Column('modbus_rtu', sa.Boolean(), nullable=False),
    sa.Column('modbus_tcp', sa.Boolean(create_constraint=80), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('setting_influx',
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('uuid', sa.String(length=80), nullable=False),
    sa.Column('host', sa.String(length=80), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('database', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('ssl', sa.Boolean(), nullable=False),
    sa.Column('verify_ssl', sa.Boolean(), nullable=False),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('timer', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=80), nullable=False),
    sa.Column('measurement', sa.String(length=80), nullable=False),
    sa.Column('attempt_reconnect_secs', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('setting_mqtt',
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('uuid', sa.String(length=80), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('host', sa.String(length=80), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('authentication', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('keepalive', sa.Integer(), nullable=False),
    sa.Column('qos', sa.Integer(), nullable=False),
    sa.Column('attempt_reconnect_on_unavailable', sa.Boolean(), nullable=False),
    sa.Column('attempt_reconnect_secs', sa.Integer(), nullable=False),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('retain_clear_interval', sa.Integer(), nullable=False),
    sa.Column('publish_value', sa.Boolean(), nullable=False),
    sa.Column('topic', sa.String(length=80), nullable=False),
    sa.Column('listen', sa.Boolean(), nullable=False),
    sa.Column('listen_topic', sa.String(length=80), nullable=False),
    sa.Column('publish_debug', sa.Boolean(), nullable=False),
    sa.Column('debug_topic', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('setting_postgres',
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('uuid', sa.String(length=80), nullable=False),
    sa.Column('host', sa.String(length=80), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('dbname', sa.String(length=80), nullable=False),
    sa.Column('user', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('ssl_mode', sa.String(length=80), nullable=False),
    sa.Column('connect_timeout', sa.Integer(), nullable=False),
    sa.Column('timer', sa.Integer(), nullable=False),
    sa.Column('table_prefix', sa.String(length=80), nullable=False),
    sa.Column('attempt_reconnect_secs', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('setting_services',
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('uuid', sa.String(length=80), nullable=False),
    sa.Column('mqtt', sa.Boolean(create_constraint=80), nullable=False),
    sa.Column('histories', sa.Boolean(), nullable=False),
    sa.Column('cleaner', sa.Boolean(create_constraint=80), nullable=False),
    sa.Column('history_sync_influxdb', sa.Boolean(create_constraint=80), nullable=False),
    sa.Column('history_sync_postgres', sa.Boolean(create_constraint=80), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('setting_services')
    op.drop_table('setting_postgres')
    op.drop_table('setting_mqtt')
    op.drop_table('setting_influx')
    op.drop_table('setting_drivers')
    # ### end Alembic commands ###
