"""empty message

Revision ID: 8aaad40acc24
Revises: 0cff86604ac8
Create Date: 2021-08-01 11:08:39.289832

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8aaad40acc24'
down_revision = '0cff86604ac8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mappings_mp_gbp')
    op.drop_table('modbus_points')
    op.drop_table('modbus_devices')
    op.drop_table('modbus_networks')

    delete_point_stores = "DELETE FROM point_stores " \
                          "WHERE point_uuid IN (SELECT uuid FROM points WHERE driver='MODBUS')"
    op.execute(delete_point_stores)
    delete_priority_array = "DELETE FROM priority_array " \
                            "WHERE point_uuid IN (SELECT uuid FROM points WHERE driver='MODBUS')"
    op.execute(delete_priority_array)
    delete_generic_points = "DELETE FROM points WHERE driver='MODBUS'"
    op.execute(delete_generic_points)
    delete_generic_devices = "DELETE FROM devices WHERE driver='MODBUS'"
    op.execute(delete_generic_devices)
    delete_generic_devices = "DELETE FROM networks WHERE driver='MODBUS'"
    op.execute(delete_generic_devices)

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('driver')

    with op.batch_alter_table('networks', schema=None) as batch_op:
        batch_op.drop_column('driver')

    with op.batch_alter_table('points', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disable_mqtt', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(
            sa.Column('type', sa.Enum('INT', 'FLOAT', 'STRING', 'BOOL', name='genericpointtype'), nullable=False,
                      server_default='FLOAT'))
        batch_op.add_column(sa.Column('unit', sa.String(), nullable=True))
        batch_op.drop_column('driver')
    # generic_points to points
    gp_to_p = 'UPDATE points SET (disable_mqtt,type,unit)=(SELECT disable_mqtt,type,unit FROM generic_points ' \
              'WHERE points.uuid = generic_points.uuid)'
    op.execute(gp_to_p)
    op.drop_table('generic_points')
    op.drop_table('generic_networks')
    op.drop_table('generic_devices')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
