"""empty message

Revision ID: 3c3879dd7969
Revises: 9d4664e1c189
Create Date: 2021-06-02 06:09:30.683572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c3879dd7969'
down_revision = '9d4664e1c189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mappings_mp_gbp')
    op.create_table('mappings_mp_gbp',
                    sa.Column('created_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=True),
                    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=True),
                    sa.Column('uuid', sa.String(), nullable=False),
                    sa.Column('point_uuid', sa.String(), nullable=False),
                    sa.Column('mapped_point_uuid', sa.String(length=80), nullable=True),
                    sa.Column('point_name', sa.String(length=80), nullable=False),
                    sa.Column('mapped_point_name', sa.String(length=80), nullable=True),
                    sa.Column('type', sa.Enum('GENERIC', 'BACNET', name='maptype'), nullable=True),
                    sa.Column('mapping_state', sa.Enum('MAPPED', 'BROKEN', name='mappingstate'), nullable=True),
                    sa.ForeignKeyConstraint(['point_uuid'], ['modbus_points.uuid'], ),
                    sa.PrimaryKeyConstraint('uuid'),
                    sa.UniqueConstraint('mapped_point_uuid'),
                    sa.UniqueConstraint('mapped_point_uuid')
                    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mappings_mp_gbp')
    op.create_table('mappings_mp_gbp',
                    sa.Column('created_on', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=True),
                    sa.Column('updated_on', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=True),
                    sa.Column('uuid', sa.VARCHAR(), nullable=False),
                    sa.Column('modbus_point_uuid', sa.VARCHAR(), nullable=False),
                    sa.Column('generic_point_uuid', sa.VARCHAR(length=80), nullable=True),
                    sa.Column('bacnet_point_uuid', sa.VARCHAR(length=80), nullable=True),
                    sa.Column('modbus_point_name', sa.VARCHAR(length=80), nullable=False),
                    sa.Column('generic_point_name', sa.VARCHAR(length=80), nullable=True),
                    sa.Column('bacnet_point_name', sa.VARCHAR(length=80), nullable=True),
                    sa.ForeignKeyConstraint(['modbus_point_uuid'], ['modbus_points.uuid'], ),
                    sa.PrimaryKeyConstraint('uuid'),
                    sa.UniqueConstraint('bacnet_point_uuid'),
                    sa.UniqueConstraint('generic_point_uuid')
                    )

    # ### end Alembic commands ###
