"""empty message

Revision ID: b4280f5228d8
Revises: 8aaad40acc24
Create Date: 2021-08-14 13:13:50.754464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4280f5228d8'
down_revision = '8aaad40acc24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history_sync_details',
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('POSTGRES', 'INFLUX', name='historysynctype'), nullable=False, server_default='POSTGRES'),
    sa.Column('details', sa.String(length=320), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('history_sync_logs',
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('POSTGRES', 'INFLUX', name='historysynctype'), nullable=False, server_default='POSTGRES'),
    sa.Column('point_uuid', sa.String(), nullable=False),
    sa.Column('last_sync_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['point_uuid'], ['points.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'point_uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history_sync_logs')
    op.drop_table('history_sync_details')
    # ### end Alembic commands ###
