"""empty message

Revision ID: 0cff86604ac8
Revises: 8c48124a6383
Create Date: 2021-07-14 18:12:50.259836

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
from sqlalchemy.orm import Session

revision = '0cff86604ac8'
down_revision = '8c48124a6383'
branch_labels = None
depends_on = None

session = Session(bind=op.get_bind())
session.execute('PRAGMA foreign_keys = OFF;')
session.commit()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('points', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('points', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('source', sa.Enum('OWN', 'MAPPING', name='sources'), server_default="OWN"))

    # ### end Alembic commands ###
