"""empty message

Revision ID: 12b42259c807
Revises: 14241c0d3431
Create Date: 2021-08-25 18:51:15.332075

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '12b42259c807'
down_revision = '14241c0d3431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('points', schema=None) as batch_op:
        batch_op.alter_column('fallback_value',
                              server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('points', schema=None) as batch_op:
        batch_op.alter_column('fallback_value',
                              server_default='16')

    # ### end Alembic commands ###
