"""empty message

Revision ID: 9d4664e1c189
Revises: 0d49c71ddb03
Create Date: 2021-05-20 13:17:12.288749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d4664e1c189'
down_revision = '0d49c71ddb03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('points', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.Enum('OWN', 'MAPPING', name='sources'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('points', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###
