"""empty message

Revision ID: 14241c0d3431
Revises: b4280f5228d8
Create Date: 2021-08-17 12:52:25.731323

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '14241c0d3431'
down_revision = 'b4280f5228d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('points', schema=None) as batch_op:
        batch_op.alter_column('fallback_value',
                              existing_type=sa.FLOAT(),
                              nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('points', schema=None) as batch_op:
        batch_op.alter_column('fallback_value',
                              existing_type=sa.FLOAT(),
                              nullable=False,
                              existing_server_default=sa.text("'16'"))

    # ### end Alembic commands ###
